### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by srnyx** [dvitski/direbats#15]
**Is your feature request related to a problem? Please describe.**
The sounds the bat makes are much louder compared to other mobs.

**Describe the solution you'd like**
The sounds that the bat makes to be quieter and not reach that far.

**Describe alternatives you've considered**
Mute my game or hostile creatures... but just... no...

**Comment by dvitski** [comment]
Direbat sounds are actually already coded to have 15% of the volume of any other mob, so I'm afraid the only option here is to use the built-in Minecraft features for this very issue and turn down hostile creatures slightly

https://github.com/teamhollow/direbats/blob/0f5dbf627020a2779804f6f855d35daa9f1debc9/src/main/java/net/teamhollow/direbats/entity/direbat/DirebatEntity.java#L127-L130
