### ISSUE TITLE
[NoSuchMethodError] Client method called in a dedicated server environment

### ISSUE THREAD

**Issue by ghost** [dvitski/direbats#16]
When I get the enhanced celestials mod on, and pump out around 300 direbats, for some reason the server may just crash. 

When removing JUST the direbats mod, my server runs perfectly fine even when I have around 2k mobs exploding stuff and what not.

Maybe it's when a direbat picks up a modded item???
[crash-2021-04-02_15.54.58-server.txt](https://github.com/teamhollow/direbats/files/6251537/crash-2021-04-02_15.54.58-server.txt)

**Comment by FoxSamu** [comment]
The more bats you spawn, the more chance you reach an exceptional case where a bat just crashes the game by spawning item particles. And you just found that case :P
Weird enough, Direbats tries to use some method that doesn't even exist:
```
net.minecraft.class_243.method_31033(F)Lnet/minecraft/class_243;
```
Not sure what this method is right now, but we'll figure it out

**Comment by andantedevs** [comment]
@JeremyGreen8 for context, are you running on a dedicated server?

**Comment by dvitski** [comment]
How does this build hold up?
https://github.com/teamhollow/direbats/packages/388576

to download, it's the first asset in the list to the right

**Comment by ghost** [comment]
> 
> 
> How does this build hold up?
> https://github.com/teamhollow/direbats/packages/388576
> 
> to download, it's the first asset in the list to the right

I'm sorry, I rarely check this website, but yes, this build fixed the issue. 

I should have also stated that yes, I am running a server and going in my own server, and that I am using fabric specifically.

**Comment by TinyAtomss** [comment]
yeah probably

**Comment by celophys** [comment]
I have the same error but with 1.18.1
