### ISSUE TITLE
Direbat fang arrow crashes server when hitting a mob

### ISSUE THREAD

**Issue by varencilator** [dvitski/direbats#17]
## Expected Behavior

Don't crash server, hits mob normally.

## Current Behavior

Crashes server due to ticking entity. DirebatFangEntity cannot be cast to net.minecraft.class_1667
at etc etc

**Comment by dvitski** [comment]
It would be quite useful if we could have the full crash report please

**Comment by varencilator** [comment]
yup

[crash-2021-04-26_01.40.58-server.txt](https://github.com/teamhollow/direbats/files/6374807/crash-2021-04-26_01.40.58-server.txt)
[crash-2021-04-26_02.06.04-server.txt](https://github.com/teamhollow/direbats/files/6374808/crash-2021-04-26_02.06.04-server.txt)

**Comment by dvitski** [comment]
Thanks!

Based on that, Articles of Temerant isn't checking its casts :(

https://github.com/Arathain/articles-of-temerant/blob/82dfcb377e03bac8f833c747f719d8da38c801fd/src/main/java/net/arathain/aot/mixin/DamageSourceMixin.java#L19
