### ISSUE TITLE
[1.18.1 Fabric] Crashes at init with other mods such as Bumblezone

### ISSUE THREAD

**Issue by TelepathicGrunt** [dvitski/direbats#22]
I have received this issue report on my bumblezone mod: https://github.com/TelepathicGrunt/Bumblezone-Fabric/issues/37

After looking at the stacktrace, it seems the issue comes down to this mixin from Direbats. 
https://github.com/andantet/direbats/blob/fabric/1.18/src/main/java/net/teamhollow/direbats/mixin/DefaultBiomeFeaturesMixin.java

Basically, the mixin is firing at game startup but so early that Fabric API and minecraft does not have all of its data/fields setup and so with certain mod combinations, Direbat's classloading causes issues or crashes as seen here.

The big problem is this mixin is not the correct way to add mobs to biomes as well. Instead, BiomeModification API from Fabric API should be used instead. Example:

```java
BiomeModifications.addSpawn(
     BiomeSelectors.categories(Biome.BiomeCategory.NETHER)
          .or(BiomeSelectors.categories(Biome.BiomeCategory.THEEND)
               .or(BiomeSelectors.categories(Biome.BiomeCategory.NONE))),
     MobCategory.MONSTER,
     EntityType.CREEPER,
     100,
     1, 
     4
 );
```

The benefit of this API way of adding to biomes is you have better control of which biome can spawn the mob, it works for datapack biomes, and does not cause any weird issues with classloading stuff too early before it is ready for usage. Much better mod compat and will now work with popular worldgen datapacks like Terralith.

**Comment by dvitski** [comment]
I used this in previous versions of Direbats, but for the 1.18 update I guess I just used a mixin as a lazy way to fix a few bugs with spawning
Of course as with any bug fix, everything shatters around it - I'll get an update out soon 😅
