### ISSUE TITLE
The direbat fang arrow entity has no entity model

### ISSUE THREAD

**Issue by iDoomful** [dvitski/direbats#6]
What should happen: When you shoot a direbat fang arrow with either a bow or crossbow, the arrow entity should be visible, just like a normal arrow

What actually happens: When you shoot the fang arrow, it doesn't have an entity model, making it invisible. The entity still exists, as you can go to the shot block and pick the arrow as an item.

Solution: Add a model for the arrow entity

1. Get a bow or crossbow (both can shoot the fang arrow when I tested)
2. Shoot at a block
3. Notice that the arrow entity is not flung into the block as you'd expect. It's there, but invisible

Here is a video of the steps: https://streamable.com/ix9n7z

Minecraft version: 1.16.3
Mod version: 1.0.0 (fabric)
All my mods: https://ibb.co/m0P7YV6 https://ibb.co/WzSmNKL

**Comment by dvitski** [comment]
It has a model, but the packet for the entity spawn isn't sent to the client :P This is a known bug but I've no idea how to get packets working lmao
